name: AWS OIDC

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:  # 手動実行用に追加

permissions:
  id-token: write
  contents: read

jobs:
  aws-oidc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          # Secretsを使わず、ARNを直書きしてテストします
          role-to-assume: arn:aws:iam::921810471152:role/github-oidc-Role

      - name: Print Hello World plan
        run: echo "Hello, aws Plan"